### ISSUE TITLE
Could not call constructor - Error on server start

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#14]
```

[18:52:30] [Server thread/INFO]: [GPAuctions] Enabling GPAuctions v1.0.beta commit 45d0d54
--
[18:52:30] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:50) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:100) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:137) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.13.2.jar:git-Paper-510]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:45) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:27) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[18:52:30] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:50) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:100) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:137) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.13.2.jar:git-Paper-510]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:45) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:27) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]


```

**Comment by NullCase** [comment]
OK, i deleted the old auction data & config. It worked.

**Comment by RoboMWM** [comment]
No, this was an issue with it loading an auction.

**Comment by NullCase** [comment]
Thanks for double checking!

**Comment by RoboMWM** [comment]
Actually, this could've been caused by the old data file. I added a field to store the sign location so it can be updated. But if this were the case I would be expecting a NPE, not a cast exception... I wonder if the sign was removed or not stored properly. I'll add debug messages here for this.

**Comment by NullCase** [comment]
It seems like this is solved in Beta 2 because GPActions loaded with auctions on file. Here's the log.

```

[21:39:07] [Server thread/INFO]: [GPAuctions] Enabling GPAuctions v1.0.beta2 commit 8cad3e1
--
[21:39:07] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-67.0,y=68.0,z=0.0,pitch=0.0,yaw=0.0}
[21:39:07] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-133.0,y=64.0,z=6.0,pitch=0.0,yaw=0.0}
[21:39:07] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-133.0,y=64.0,z=-20.0,pitch=0.0,yaw=0.0}
[21:39:07] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-58.0,y=68.0,z=10.0,pitch=0.0,yaw=0.0}
[21:39:07] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-139.0,y=64.0,z=-10.0,pitch=0.0,yaw=0.0}


```

**Comment by NullCase** [comment]
It looks like your "sign was removed" guess is a good one.

Yesterday I removed at least one auction sign while testing bids.

Today while testing another update: 
- First server startup, no error.
- Restarted the server, this error appeared. (below)

How about I test this formally tomorrow? 
- Make a new auctions.data.
- Create one auction. Remove sign.
- Restart to see if I can produce the bug.

```

[00:05:05] [Server thread/INFO]: [GPAuctions] Enabling GPAuctions v1.0.beta2 commit 8cad3e1
--
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-67.0,y=68.0,z=0.0,pitch=0.0,yaw=0.0}
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-122.0,y=64.0,z=-11.0,pitch=0.0,yaw=0.0}
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-133.0,y=64.0,z=6.0,pitch=0.0,yaw=0.0}
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-133.0,y=64.0,z=-20.0,pitch=0.0,yaw=0.0}
[00:05:05] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:51) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:100) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:137) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.13.2.jar:git-Paper-522]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:45) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:27) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-522]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-58.0,y=68.0,z=10.0,pitch=0.0,yaw=0.0}
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-142.0,y=64.0,z=7.0,pitch=0.0,yaw=0.0}
[00:05:05] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-139.0,y=64.0,z=-10.0,pitch=0.0,yaw=0.0}

```

**Comment by NullCase** [comment]
How did you guess?

New .data file. Made auction. Removed sign. Error on startup.

It seems like you're 100% right.

```

[00:24:00] [Server thread/INFO]: [GPAuctions] Enabling GPAuctions v1.0.beta2 commit 8cad3e1
--
[00:24:00] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-123.0,y=64.0,z=-11.0,pitch=0.0,yaw=0.0}
[00:24:00] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:51) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:100) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:137) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.13.2.jar:git-Paper-522]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.13.2.jar:git-Paper-522]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:45) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:27) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-522]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-522]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-522]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

```
