### ISSUE TITLE
[bug] Could not pass event SignChangeEvent

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#19]
```

[05:37:01] [Server thread/INFO]: [GPAuctions] SignChangeEvent called
--
[05:37:01] [Server thread/INFO]: [GPAuctions] Line 1 matched sign
[05:37:01] [Server thread/ERROR]: Could not pass event SignChangeEvent to GPAuctions v1.0.beta2 commit 422d10b
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-523]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-523]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-523]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2549) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-523]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-523]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
at com.robomwm.gpauctions.Config.asInt(Config.java:63) ~[?:?]
at com.robomwm.gpauctions.listener.CreateAuctionListener.onSignChange(CreateAuctionListener.java:49) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-523]
... 15 more

```
Ignore all of this if you already know what's wrong.

Possible explanation: Windows updated for me this morning. Starting the test/offline server today I was unable to check for Vault updates. When trying to join it says authentication servers are down. I had to switch the server to "offline mode" in server properties in order to join. I joined as "Steve" skin and my own claims did not recognize me so it seems like my UUID is not checked/not matching. If you're checking for UUID then perhaps that's the problem here. Either way, this is to remind me later.

https://support.microsoft.com/en-us/help/4487080/security-and-quality-rollup-updates-for-net-framework-3-5-to-4-7-2

**Comment by RoboMWM** [comment]
Yeah, I apparently tried to retrieve a value as an int instead of as a double. Currently in an area with limited internet, will try to push changes when I get a chance

**Comment by NullCase** [comment]
For testing I defined the default auction length as 0.1 hours.

A double for auction duration sounds great because once variable auction lengths are built the players will definitely run short auctions.

**Comment by RoboMWM** [comment]
Yea, was about to ask what your value was. I'm expecting an int value there. I don't know how the converter will handle double values but I guess I could do that instead.

**Comment by NullCase** [comment]
It sounds like your thinking converting a double might cause some problems. How can we test that out?
