### ISSUE TITLE
Bidding Test Results

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#22]
Test: Create auction, right click it's sign to bid.
Result: Sign does not update but console messages show that GPA is recognizing the click:

```
[GPAuctions] Sign clicked
[GPAuctions] Is a real estate-labeled sign
[GPAuctions] claim found
[GPAuctions] auction found
```

Bids are not listed in auction.data.

Shift + clicking the sign shows the original price.

Expected result: Sign updates with new price. Shift+clicking sign displays new price with bidder. "successful bid" message.

**Comment by RoboMWM** [comment]
Does the player bidding have enough money?

**Comment by NullCase** [comment]
Ah! insufficient balance. It looks like the the message from https://github.com/RoboMWM/GPAuctions/issues/2 is not sent.

It looks like the latest release failed but the previous one threw this error when I had sufficient funds.

```

[17:16:25] [Server thread/INFO]: [GPAuctions] Is a real estate-labeled sign
--
[17:16:25] [Server thread/INFO]: [GPAuctions] addBid called
[17:16:25] [Server thread/INFO]: [GPAuctions] claim found
[17:16:25] [Server thread/INFO]: [GPAuctions] auction found
[17:16:25] [Server thread/INFO]: [GPAuctions] sufficient balance
[17:16:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GPAuctions v1.0.beta2 commit 422d10b
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-524]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-524]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-524]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.util.EmptyStackException
at java.util.Stack.peek(Unknown Source) ~[?:1.8.0_201]
at com.robomwm.gpauctions.auction.Auction.addBid(Auction.java:101) ~[?:?]
at com.robomwm.gpauctions.auction.Auctioneer.addBid(Auctioneer.java:146) ~[?:?]
at com.robomwm.gpauctions.listener.MakeBidListener.onSignClick(MakeBidListener.java:62) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.13.2.jar:git-Paper-524]
... 17 more

```

**Comment by RoboMWM** [comment]
Latest build should resolve this problem, as I also fixed a control flow issue which is what this is related to.

**Comment by NullCase** [comment]
thanks RoboMWM. control flow?

**Comment by NullCase** [comment]
```
[16:59:16] [Server thread/INFO]: [GPAuctions] Sign clicked
--
[16:59:16] [Server thread/INFO]: [GPAuctions] Is a real estate-labeled sign
[16:59:16] [Server thread/INFO]: [GPAuctions] addBid called
[16:59:16] [Server thread/INFO]: [GPAuctions] claim found
[16:59:16] [Server thread/INFO]: [GPAuctions] auction found
[16:59:16] [Server thread/INFO]: [GPAuctions] sufficient balance
[16:59:16] [Server thread/INFO]: [GPAuctions] checking conditions before adding bid to auction...
[16:59:16] [Server thread/INFO]: [GPAuctions] auction has not ended.
[16:59:16] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GPAuctions v1.0.beta2 commit 8011771
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-524]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-524]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-524]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.util.EmptyStackException
at java.util.Stack.peek(Unknown Source) ~[?:1.8.0_201]
at com.robomwm.gpauctions.auction.Auction.addBid(Auction.java:106) ~[?:?]
at com.robomwm.gpauctions.auction.Auctioneer.addBid(Auctioneer.java:146) ~[?:?]
at com.robomwm.gpauctions.listener.MakeBidListener.onSignClick(MakeBidListener.java:62) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.13.2.jar:git-Paper-524]
... 17 more

```

**Comment by RoboMWM** [comment]
hmm, I guess I'm still messing up my if else logic somehow.

**Comment by NullCase** [comment]
I don't know how to code, but if you post the segment in question it seems like a logic problem.

I can do logic problems.

**Comment by NullCase** [comment]
This looks fixed to me. I'll try to break it.

Didn't break it. This works really well.
