### ISSUE TITLE
[bug] Could not pass SignChangeEvent in f0d90a7

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#24]
```
[09:29:21] [Server thread/INFO]: [GriefPrevention] NullCase placed a sign @ world: x-58, z11;[ac];10000
--
[09:29:21] [Server thread/INFO]: [GPAuctions] SignChangeEvent called
[09:29:21] [Server thread/INFO]: [GPAuctions] Line 1 matched sign
[09:29:21] [Server thread/ERROR]: Could not pass event SignChangeEvent to GPAuctions v1.0.beta2 commit f0d90a7
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-524]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2549) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-524]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-524]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at com.robomwm.gpauctions.Config.asLong(Config.java:58) ~[?:?]
at com.robomwm.gpauctions.listener.CreateAuctionListener.onSignChange(CreateAuctionListener.java:49) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-524]
... 15 more

```

**Comment by RoboMWM** [comment]
Huh, it can't implicitly cast? Ugh.

**Comment by NullCase** [comment]
it looks like the latest version solves this.
