### ISSUE TITLE
Finalize auction system: remaining features.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#30]
This is listed as Phase 3 in your summary.

---------
1) Auctions transfer already. After an auction ended with bidders it transferred to a bidder. 

_Note: The bidder was just me, but the highest bid amount was used (good!)._

Remaining to test: 
- ~~various bidders on a single auction.~~
- ~~bidders who do not have money when the auction closes.~~
- ~~Confirm highest bidder is the only one who wins.~~
- ~~Try to break it more.~~

---------------

2) Updating the sign when auction closes.

- Sign update as described in #28
- Presently, the auction ends and the sign remains. 
- Right clicking the sign with funds says "You have insufficient funds to place a bid at this time." 
- Shift + Right clicking the sign generates this error.
```
[02:35:16] [Server thread/INFO]: [GPAuctions] Sign clicked
--
[02:35:16] [Server thread/INFO]: [GPAuctions] Is a real estate-labeled sign
[02:35:16] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GPAuctions v1.0.beta2 commit b5adf47
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-551]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-551]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-551]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-551]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-551]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-551]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-551]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
at com.robomwm.gpauctions.listener.MakeBidListener.getInfo(MakeBidListener.java:81) ~[?:?]
at com.robomwm.gpauctions.listener.MakeBidListener.onSignClick(MakeBidListener.java:58) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.13.2.jar:git-Paper-551]
... 17 more

```

**Comment by RoboMWM** [comment]
I'm assuming the rest are notes for you, as the only action item I see here is the stacktrace.

You can group issues with the milestone system (simple) and/or with the project system (more involved)

**Comment by RoboMWM** [comment]
Resolved NPE in https://github.com/RoboMWM/GPAuctions/commit/49b4e84e7916dd6be1246e74b102189cf4ce62fe

Will leave open for the rest of your notes

**Comment by NullCase** [comment]
Bids are listed in the .data file.

It seems like thousands of bids could occur. quite fast too.

Do you think that might ever be a problem?

**Comment by NullCase** [comment]
Hey @RoboMWM 

Phase 3 might be done, but it seems like I'm forgetting something important. I'll have headspace in a few days to work that out.
