### ISSUE TITLE
1.14.4 Could not call constructor... Error on server start. 

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#58]
It looks like the signs are in place this time, but the sign might actually be different because of 1.14?

Reference: https://github.com/RoboMWM/GPAuctions/issues/14

```

[05:08:03] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-1672.0,y=77.0,z=-628.0,pitch=0.0,yaw=0.0}
--
[05:08:03] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:57) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:105) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:143) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.14.4.jar:git-Paper-149]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.14.4.jar:git-Paper-149]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:51) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:34) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-149]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-149]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[05:08:03] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=160.0,y=64.0,z=-547.0,pitch=0.0,yaw=0.0}


```

**Comment by RoboMWM** [comment]
Idk if you can check location of signs and verify the block at each location?

**Comment by NullCase** [comment]
i can check, sure. What's the coordinates for this particular error? is there a way to tell?

because my first guess was the one above or below. signs are at both of those.

**Comment by NullCase** [comment]
well that's funny. I just booted up the server to double check, to scower the list manually....

This time it booted up without any trouble. The error message is gone.

With 1.14.4 updates going on daily, I'll leave this open to see if it reappears. Idk what the cause is yet or how to find out.

**Comment by NullCase** [comment]
After #59 and after removing the partially removed auction.

```
[11:36:41] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-3398.0,y=88.0,z=367.0,pitch=0.0,yaw=0.0}
--
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-240.0,y=94.0,z=3276.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-503.0,y=66.0,z=-1012.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=616.0,y=68.0,z=-206.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=537.0,y=75.0,z=497.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:57) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:105) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:143) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.14.4.jar:git-Paper-154]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:51) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:34) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-154]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-154]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-154]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-154]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-76.0,y=76.0,z=56.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-63.0,y=72.0,z=51.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-96.0,y=79.0,z=87.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=601.0,y=78.0,z=-202.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:57) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:105) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:143) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.14.4.jar:git-Paper-154]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.14.4.jar:git-Paper-154]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:51) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:34) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-154]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-154]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-154]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-154]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-154]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=1152.0,y=63.0,z=-1552.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world_nether},x=-296.0,y=128.0,z=346.0,pitch=0.0,yaw=0.0}
[11:36:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=2842.0,y=80.0,z=-2131.0,pitch=0.0,yaw=0.0}
```

**Comment by NullCase** [comment]
after creating and canceling a new auction (thinking here was to update the .data file), and then restarting the server.

Now it looks fine again.
```
[11:38:41] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-96.0,y=79.0,z=87.0,pitch=0.0,yaw=0.0}
--
[11:38:41] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-3398.0,y=88.0,z=367.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=616.0,y=68.0,z=-206.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=1152.0,y=63.0,z=-1552.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-240.0,y=94.0,z=3276.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world_nether},x=-296.0,y=128.0,z=346.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-503.0,y=66.0,z=-1012.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-76.0,y=76.0,z=56.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=2842.0,y=80.0,z=-2131.0,pitch=0.0,yaw=0.0}
[11:38:42] [Server thread/INFO]: [GPAuctions] sign location load Location{world=CraftWorld{name=world},x=-63.0,y=72.0,z=51.0,pitch=0.0,yaw=0.0}


```

**Comment by RoboMWM** [comment]
Yea, probably inconsistent state of file causing the location to be improperly loaded. It's getting some sort of a location (else there would be a cast exception on loading). I could add debug message to print out the object on load if this is still an issue with the 1.2.2 release.
