### ISSUE TITLE
Auction saved to file. Test results for Feb 1 2019

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#6]
Created auction.
It saved.
Restarted. Error thrown.
Created new auction (different claim). The new auction saved but the old auction was no longer in the auctions.data file.

contents of auctions.data after first auction created.
```
'2405':
  ==: com.robomwm.gpauctions.auction.Auction
  startingBid: 884.0
  bids: []
  claimID: 2405
  endTime: 1551650138690
```
---

When restarting, here's the error

```
[17:01:22] [Server thread/INFO]: [GPAuctions] Enabling GPAuctions v1.0.alpha commit 8095d45
--
[17:01:22] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call constructor 'public com.robomwm.gpauctions.auction.Auction(java.util.Map)' of class com.robomwm.gpauctions.auction.Auction for deserialization
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at com.robomwm.gpauctions.auction.Auction.<init>(Auction.java:36) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:100) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:137) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.13.2.jar:git-Paper-510]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.13.2.jar:git-Paper-510]
at com.robomwm.gpauctions.auction.Auctioneer.<init>(Auctioneer.java:30) ~[?:?]
at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:26) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by RoboMWM** [comment]
Use 3 backticks to create a code block

    ```
    like this 
    ```
