### ISSUE TITLE
auctions can't be started on admin claims

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#8]
This sign was placed on an admin claim (i was not admin) I will test this part more.

Also, I used a negative number which failed to create an auction but did clear all permissions on the claim. What do you want to do for that?

[19:17:53] [Server thread/INFO]: [GriefPrevention] NullCase placed a sign @ world: x-60, z0;[ac];-100000
--
[19:17:53] [Server thread/INFO]: [GPAuctions] SignChangeEvent called
[19:17:53] [Server thread/INFO]: [GPAuctions] Line 1 matched sign
[19:17:53] [Server thread/INFO]: [GPAuctions] Claim found
[19:17:53] [Server thread/INFO]: [GPAuctions] Set starting bid to -100000.0
[19:17:53] [Server thread/INFO]: [GPAuctions] addAuction called
[19:17:53] [Server thread/INFO]: [GPAuctions] Pre-existing auction does not exist.
[19:17:53] [Server thread/INFO]: [GPAuctions] Set claim owner to null (admin claim) and cleared trustlist
[19:17:53] [Server thread/ERROR]: Could not pass event SignChangeEvent to GPAuctions v1.0.beta commit c913acc
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-510]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2548) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-510]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_201]
at me.ryanhamshire.GriefPrevention.DataStore.getPlayerData(DataStore.java:560) ~[?:?]
at com.robomwm.gpauctions.auction.Auctioneer.addAuction(Auctioneer.java:85) ~[?:?]
at com.robomwm.gpauctions.listener.CreateAuctionListener.onSignChange(CreateAuctionListener.java:68) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-510]
... 15 more

**Comment by RoboMWM** [comment]
I'll use the absolute value, thanks for reporting.

**Comment by NullCase** [comment]
OK, the error was because of the Admin claim.

because:
1) I was able to create a -$ auction on my own claim.
2) I was also able to create an auction as a trusted player on someone else's claim.

So negative values were working. The error is from Auctioning an Admin claim. So I tried again to create an auction but this time as OP. here's the error.

```

[19:39:13] [Server thread/INFO]: [GriefPrevention] NullCase placed a sign @ world: x-60, z0;[ac]
--
[19:39:13] [Server thread/INFO]: [GPAuctions] SignChangeEvent called
[19:39:13] [Server thread/INFO]: [GPAuctions] Line 1 matched sign
[19:39:13] [Server thread/INFO]: [GPAuctions] Claim found
[19:39:13] [Server thread/INFO]: [GPAuctions] Set starting bid to 1440.0
[19:39:13] [Server thread/INFO]: [GPAuctions] addAuction called
[19:39:13] [Server thread/INFO]: [GPAuctions] Pre-existing auction does not exist.
[19:39:13] [Server thread/INFO]: [GPAuctions] Set claim owner to null (admin claim) and cleared trustlist
[19:39:13] [Server thread/ERROR]: Could not pass event SignChangeEvent to GPAuctions v1.0.beta commit c913acc
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-510]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2548) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-510]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_201]
at me.ryanhamshire.GriefPrevention.DataStore.getPlayerData(DataStore.java:560) ~[?:?]
at com.robomwm.gpauctions.auction.Auctioneer.addAuction(Auctioneer.java:85) ~[?:?]
at com.robomwm.gpauctions.listener.CreateAuctionListener.onSignChange(CreateAuctionListener.java:68) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-510]
... 15 more


```

**Comment by RoboMWM** [comment]
Can't recall if the econ plugin uses absolute value by default (since it has methods for depositing and withdrawing, and negatives don't work here - I think I recall from debugging another plugin it automatically used the absolute value).

Seems I didn't account for auctions owned by admins, will fix that thanks.
