### ISSUE TITLE
Creating an auction on claim where you are trusted, error.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#9]
Sign placed inside subclaim where I am trusted.

[19:26:44] [Server thread/INFO]: [GriefPrevention] NullCase placed a sign @ world: x-134, z-48;[ac]
--
[19:26:44] [Server thread/INFO]: [GPAuctions] SignChangeEvent called
[19:26:44] [Server thread/INFO]: [GPAuctions] Line 1 matched sign
[19:26:44] [Server thread/INFO]: [GPAuctions] Claim found
[19:26:44] [Server thread/INFO]: [GPAuctions] Set starting bid to 1219.0
[19:26:44] [Server thread/INFO]: [GPAuctions] addAuction called
[19:26:44] [Server thread/INFO]: [GPAuctions] Pre-existing auction does not exist.
[19:26:44] [Server thread/ERROR]: Could not pass event SignChangeEvent to GPAuctions v1.0.beta commit c913acc
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-510]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2548) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-510]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
at com.robomwm.gpauctions.auction.Auctioneer.addAuction(Auctioneer.java:82) ~[?:?]
at com.robomwm.gpauctions.listener.CreateAuctionListener.onSignChange(CreateAuctionListener.java:68) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-510]
... 15 more

**Comment by NullCase** [comment]
OK, outside of a subclaim, anyone with build permissions can create an auction.

No error thrown. the auction is created successfully.

**Comment by RoboMWM** [comment]
Huh, I guess it's not possible to obtain subclaims by their claim id.

Should auctions be able to be started within a subclaim? If so, should the auction apply to the parent claim?

**Comment by NullCase** [comment]
Auctioning subclaims.... hrm. What if we leave that as an *enhancement option down the road? See how people like Auctions for a bit.

So for now, let's have auctions only created outside subclaims.

How's that sound?

**Comment by RoboMWM** [comment]
Sounds good. Will add a check to simply deny auction creation if sign is placed within a subclaim.

Should trusted players be able to start an auction on a claim? Or should it be restricted to only the owner and server admins (which I just did in that commit)?

**Comment by NullCase** [comment]
Just the claim owner sounds best to me.

However, i don't know how that would work for Admin claims.

I will be able to test again tomorrow, and I'll go through your build history to find things to test.

Thanks RoboMWM! The guys are really excited about auctions.

**Comment by RoboMWM** [comment]
Anyone with griefprevention.adminclaims can start an auction on any claim.
